services:
  app:
    build: .
    container_name: scraper_api
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: scraper_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_password
      POSTGRES_DB: scraper_db
    ports:
      - "5432:5432"
    volumes:
      - scraper_pg_data:/var/lib/postgresql/data

volumes:
  scraper_pg_data: